<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
class CarModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $renault=array(
                       array('model_name'=>'100','brand_id'=>100),
                       array('model_name'=>'200','brand_id'=>100),
                       array('model_name'=>'240sx','brand_id'=>100),
                       array('model_name'=>'280','brand_id'=>100),
                       array('model_name'=>'300','brand_id'=>100),
                       array('model_name'=>'350z','brand_id'=>100),
                       array('model_name'=>'370z','brand_id'=>100),
                       array('model_name'=>'almera','brand_id'=>100),
                       array('model_name'=>'altima','brand_id'=>100),
                       array('model_name'=>'bluebird','brand_id'=>100),
                       array('model_name'=>'cabstar','brand_id'=>100),
                       array('model_name'=>'evalia','brand_id'=>100),
                       array('model_name'=>'gtr','brand_id'=>100),
                       array('model_name'=>'infiniti','brand_id'=>100),
                       array('model_name'=>'juke','brand_id'=>100),
                       array('model_name'=>'king cab','brand_id'=>100),
                       array('model_name'=>'king double cab','brand_id'=>100),
                       array('model_name'=>'kubistar','brand_id'=>100),
                       array('model_name'=>'leaf','brand_id'=>100),
                       array('model_name'=>'maxima','brand_id'=>100),
                       array('model_name'=>'micra','brand_id'=>100),
                       array('model_name'=>'murano','brand_id'=>100),
                       array('model_name'=>'navara','brand_id'=>100),
                       array('model_name'=>'note','brand_id'=>100),
                       array('model_name'=>'nv200','brand_id'=>100),
                       array('model_name'=>'pathfinder','brand_id'=>100),
                       array('model_name'=>'patrol','brand_id'=>100),
                       array('model_name'=>'pick-up','brand_id'=>100),
                       array('model_name'=>'prairie','brand_id'=>100),
                       array('model_name'=>'primastar','brand_id'=>100),
                       array('model_name'=>'primera','brand_id'=>100),
                       array('model_name'=>'qashqai','brand_id'=>100),
                       array('model_name'=>'quest ','brand_id'=>100),
                       array('model_name'=>'sentra','brand_id'=>100),
                       array('model_name'=>'serena','brand_id'=>100),
                       array('model_name'=>'sunny','brand_id'=>100),
                       array('model_name'=>'terrano','brand_id'=>100),
                       array('model_name'=>'tiida','brand_id'=>100),
                       array('model_name'=>'tino','brand_id'=>100),
                       array('model_name'=>'trade','brand_id'=>100),
                       array('model_name'=>'urvan','brand_id'=>100),
                       array('model_name'=>'vanette','brand_id'=>100),
                       array('model_name'=>'versa','brand_id'=>100),
                       array('model_name'=>'x trail','brand_id'=>100),

                       array('model_name'=>'100','brand_id'=>2),
                       array('model_name'=>'200','brand_id'=>2),
                       array('model_name'=>'80','brand_id'=>2),
                       array('model_name'=>'90','brand_id'=>2),
                       array('model_name'=>'a1','brand_id'=>2),
                       array('model_name'=>'a2','brand_id'=>2),
                       array('model_name'=>'a3','brand_id'=>2),
                       array('model_name'=>'a3 berline','brand_id'=>2),
                       array('model_name'=>'a4','brand_id'=>2),
                       array('model_name'=>'a4 allroad','brand_id'=>2),
                       array('model_name'=>'a5 coupe','brand_id'=>2),
                       array('model_name'=>'a5 SPORTBACK','brand_id'=>2),
                       array('model_name'=>'a6','brand_id'=>2),
                       array('model_name'=>'a6 allroad','brand_id'=>2),
                       array('model_name'=>'a7','brand_id'=>2),
                       array('model_name'=>'a8','brand_id'=>2),
                       array('model_name'=>'allroad','brand_id'=>2),
                       array('model_name'=>'coupe','brand_id'=>2),
                       array('model_name'=>'e-tron','brand_id'=>2),
                       array('model_name'=>'e-tron  sportback','brand_id'=>2),
                       array('model_name'=>'q2','brand_id'=>2),
                       array('model_name'=>'q3','brand_id'=>2),
                       array('model_name'=>'q3 sportback','brand_id'=>2),
                       array('model_name'=>'q5','brand_id'=>2),
                       array('model_name'=>'q7','brand_id'=>2),
                       array('model_name'=>'q8','brand_id'=>2),
                       array('model_name'=>'r8','brand_id'=>2),
                       array('model_name'=>'rs q8','brand_id'=>2),
                       array('model_name'=>'rs-q3','brand_id'=>2),
                       array('model_name'=>'rs2','brand_id'=>2),
                       array('model_name'=>'rs3','brand_id'=>2),
                       array('model_name'=>'rs4','brand_id'=>2),
                       array('model_name'=>'rs5','brand_id'=>2),
                       array('model_name'=>'rs6','brand_id'=>2),
                       array('model_name'=>'rs7','brand_id'=>2),
                       array('model_name'=>'s1','brand_id'=>2),
                       array('model_name'=>'s2','brand_id'=>2),
                       array('model_name'=>'s3','brand_id'=>2),
                       array('model_name'=>'s4','brand_id'=>2),
                       array('model_name'=>'s5','brand_id'=>2),
                       array('model_name'=>'s6','brand_id'=>2),
                       array('model_name'=>'s7','brand_id'=>2),
                       array('model_name'=>'s8','brand_id'=>2),
                       array('model_name'=>'sq5','brand_id'=>2),
                       array('model_name'=>'sq7','brand_id'=>2),
                       array('model_name'=>'sq8','brand_id'=>2),
                       array('model_name'=>'tt','brand_id'=>2),
                       array('model_name'=>'tt-rs','brand_id'=>2),
                       array('model_name'=>'tts','brand_id'=>2),
                       array('model_name'=>'v8','brand_id'=>2),

                       array('model_name'=>'0','brand_id'=>23),
                       array('model_name'=>'4runner','brand_id'=>23),
                       array('model_name'=>'auris','brand_id'=>23),
                       array('model_name'=>'avensis','brand_id'=>23),
                       array('model_name'=>'avensisverso','brand_id'=>23),
                       array('model_name'=>'aygo','brand_id'=>23),
                       array('model_name'=>'c-hr','brand_id'=>23),
                       array('model_name'=>'camry','brand_id'=>23),
                       array('model_name'=>'carina','brand_id'=>23),
                       array('model_name'=>'celica','brand_id'=>23),
                       array('model_name'=>'corolla','brand_id'=>23),
                       array('model_name'=>'corollacross','brand_id'=>23),
                       array('model_name'=>'corollaverso','brand_id'=>23),
                       array('model_name'=>'corona','brand_id'=>23),
                       array('model_name'=>'cr-h','brand_id'=>23),
                       array('model_name'=>'fjcruiser','brand_id'=>23),
                       array('model_name'=>'fortuner','brand_id'=>23),
                       array('model_name'=>'hiace','brand_id'=>23),
                       array('model_name'=>'highlander','brand_id'=>23),
                       array('model_name'=>'hilux','brand_id'=>23),
                       array('model_name'=>'landcruiser','brand_id'=>23),
                       array('model_name'=>'lexus','brand_id'=>23),
                       array('model_name'=>'liteace','brand_id'=>23),
                       array('model_name'=>'mr','brand_id'=>23),
                       array('model_name'=>'paseo','brand_id'=>23),
                       array('model_name'=>'picnic','brand_id'=>23),
                       array('model_name'=>'prado','brand_id'=>23),
                       array('model_name'=>'previa','brand_id'=>23),
                       array('model_name'=>'prius','brand_id'=>23),
                       array('model_name'=>'rav-4','brand_id'=>23),
                       array('model_name'=>'runner','brand_id'=>23),
                       array('model_name'=>'sienna','brand_id'=>23),
                       array('model_name'=>'starlet','brand_id'=>23),
                       array('model_name'=>'supra','brand_id'=>23),
                       array('model_name'=>'tercel','brand_id'=>23),
                       array('model_name'=>'tundra','brand_id'=>23),
                       array('model_name'=>'verso','brand_id'=>23),
                       array('model_name'=>'yaris','brand_id'=>23),
                       array('model_name'=>'yarisverso','brand_id'=>23),

                       array('model_name'=>'3100','brand_id'=>4),
                       array('model_name'=>'alero','brand_id'=>4),
                       array('model_name'=>'astro','brand_id'=>4),
                       array('model_name'=>'avalanche','brand_id'=>4),
                       array('model_name'=>'aveo','brand_id'=>4),
                       array('model_name'=>'beretta','brand_id'=>4),
                       array('model_name'=>'blazer','brand_id'=>4),
                       array('model_name'=>'camaro','brand_id'=>4),
                       array('model_name'=>'caprice','brand_id'=>4),
                       array('model_name'=>'captiva','brand_id'=>4),
                       array('model_name'=>'cavalier','brand_id'=>4),
                       array('model_name'=>'cmp','brand_id'=>4),
                       array('model_name'=>'corvette','brand_id'=>4),
                       array('model_name'=>'cr8','brand_id'=>4),
                       array('model_name'=>'cruze','brand_id'=>4),
                       array('model_name'=>'e400','brand_id'=>4),
                       array('model_name'=>'el camino','brand_id'=>4),
                       array('model_name'=>'epica','brand_id'=>4),
                       array('model_name'=>'evanda','brand_id'=>4),
                       array('model_name'=>'express','brand_id'=>4),
                       array('model_name'=>'hhr','brand_id'=>4),
                       array('model_name'=>'kalos','brand_id'=>4),
                       array('model_name'=>'lacetti','brand_id'=>4),
                       array('model_name'=>'maruti','brand_id'=>4),
                       array('model_name'=>'matiz','brand_id'=>4),
                       array('model_name'=>'metro','brand_id'=>4),
                       array('model_name'=>'monte-carlo','brand_id'=>4),
                       array('model_name'=>'nubira','brand_id'=>4),
                       array('model_name'=>'nubira sw','brand_id'=>4),
                       array('model_name'=>'optra','brand_id'=>4),
                       array('model_name'=>'orlando','brand_id'=>4),
                       array('model_name'=>'rezzo','brand_id'=>4),
                       array('model_name'=>'s-10','brand_id'=>4),
                       array('model_name'=>'silverado','brand_id'=>4),
                       array('model_name'=>'spark','brand_id'=>4),
                       array('model_name'=>'ssr','brand_id'=>4),
                       array('model_name'=>'suburban','brand_id'=>4),
                       array('model_name'=>'tacuma','brand_id'=>4),
                       array('model_name'=>'tahoe','brand_id'=>4),
                       array('model_name'=>'tracker','brand_id'=>4),
                       array('model_name'=>'trail blazer','brand_id'=>4),
                       array('model_name'=>'trans sport','brand_id'=>4),
                       array('model_name'=>'traverse','brand_id'=>4),
                       array('model_name'=>'trax','brand_id'=>4),
                       array('model_name'=>'uplander','brand_id'=>4),


                       array('model_name'=>'accord','brand_id'=>7),
                       array('model_name'=>'acty','brand_id'=>7),
                       array('model_name'=>'aerodeck','brand_id'=>7),
                       array('model_name'=>'city','brand_id'=>7),
                       array('model_name'=>'civic','brand_id'=>7),
                       array('model_name'=>'concerto','brand_id'=>7),
                       array('model_name'=>'cr-v','brand_id'=>7),
                       array('model_name'=>'cr-x','brand_id'=>7),
                       array('model_name'=>'fr-v','brand_id'=>7),
                       array('model_name'=>'hr-v','brand_id'=>7),
                       array('model_name'=>'insight','brand_id'=>7),
                       array('model_name'=>'integra','brand_id'=>7),
                       array('model_name'=>'jazz','brand_id'=>7),
                       array('model_name'=>'legend','brand_id'=>7),
                       array('model_name'=>'logo','brand_id'=>7),
                       array('model_name'=>'nsx','brand_id'=>7),
                       array('model_name'=>'odyssey','brand_id'=>7),
                       array('model_name'=>'prelude','brand_id'=>7),
                       array('model_name'=>'s 2000','brand_id'=>7),
                       array('model_name'=>'shuttle','brand_id'=>7),
                       array('model_name'=>'stream','brand_id'=>7),
                       array('model_name'=>'vigor','brand_id'=>7),

                       array('model_name'=>'besta','brand_id'=>11),
                       array('model_name'=>'cadenza','brand_id'=>11),
                       array('model_name'=>'carens','brand_id'=>11),
                       array('model_name'=>'carnival','brand_id'=>11),
                       array('model_name'=>'ceed','brand_id'=>11),
                       array('model_name'=>'cerato','brand_id'=>11),
                       array('model_name'=>'clarus','brand_id'=>11),
                       array('model_name'=>'combi','brand_id'=>11),
                       array('model_name'=>'k2500','brand_id'=>11),
                       array('model_name'=>'k2700','brand_id'=>11),
                       array('model_name'=>'k5','brand_id'=>11),
                       array('model_name'=>'magentis','brand_id'=>11),
                       array('model_name'=>'mohave','brand_id'=>11),
                       array('model_name'=>'niro','brand_id'=>11),
                       array('model_name'=>'opirus','brand_id'=>11),
                       array('model_name'=>'optima','brand_id'=>11),
                       array('model_name'=>'picanto','brand_id'=>11),
                       array('model_name'=>'pregio','brand_id'=>11),
                       array('model_name'=>'pride','brand_id'=>11),
                       array('model_name'=>'proceed','brand_id'=>11),
                       array('model_name'=>'quoris','brand_id'=>11),
                       array('model_name'=>'rio','brand_id'=>11),
                       array('model_name'=>'seltos','brand_id'=>11),
                       array('model_name'=>'sephia','brand_id'=>11),
                       array('model_name'=>'shuma','brand_id'=>11),
                       array('model_name'=>'sorento','brand_id'=>11),
                       array('model_name'=>'soul','brand_id'=>11),
                       array('model_name'=>'sportage','brand_id'=>11),
                       array('model_name'=>'stinger','brand_id'=>11),

                       array('model_name'=>'dokker','brand_id'=>54),
                       array('model_name'=>'duster','brand_id'=>54),
                       array('model_name'=>'lodgy','brand_id'=>54),
                       array('model_name'=>'logan','brand_id'=>54),
                       array('model_name'=>'logan mcv','brand_id'=>54),
                       array('model_name'=>'pick-up','brand_id'=>54),
                       array('model_name'=>'pick-up double cab','brand_id'=>54),
                       array('model_name'=>'sandero','brand_id'=>54),
                       array('model_name'=>'solenza','brand_id'=>54),

                       array('model_name'=>'2 cv','brand_id'=>52),
                       array('model_name'=>'ami','brand_id'=>52),
                       array('model_name'=>'ax','brand_id'=>52),
                       array('model_name'=>'berlingo','brand_id'=>52),
                       array('model_name'=>'bx','brand_id'=>52),
                       array('model_name'=>'c-crosser','brand_id'=>52),
                       array('model_name'=>'c-elysee','brand_id'=>52),
                       array('model_name'=>'c1','brand_id'=>52),
                       array('model_name'=>'c15','brand_id'=>52),
                       array('model_name'=>'c2','brand_id'=>52),
                       array('model_name'=>'c25','brand_id'=>52),
                       array('model_name'=>'c3','brand_id'=>52),
                       array('model_name'=>'c3 aircross','brand_id'=>52),
                       array('model_name'=>'c3 picasso','brand_id'=>52),
                       array('model_name'=>'c3 pluriel','brand_id'=>52),
                       array('model_name'=>'c35','brand_id'=>52),
                       array('model_name'=>'c4','brand_id'=>52),
                       array('model_name'=>'c4 aircross','brand_id'=>52),
                       array('model_name'=>'c4 cactus','brand_id'=>52),
                       array('model_name'=>'c4 picasso','brand_id'=>52),
                       array('model_name'=>'c4 spacetourer','brand_id'=>52),
                       array('model_name'=>'c5','brand_id'=>52),
                       array('model_name'=>'c5 aircross','brand_id'=>52),
                       array('model_name'=>'c6','brand_id'=>52),
                       array('model_name'=>'c8','brand_id'=>52),
                       array('model_name'=>'cx','brand_id'=>52),
                       array('model_name'=>'ds','brand_id'=>52),
                       array('model_name'=>'ds19','brand_id'=>52),
                       array('model_name'=>'ds20','brand_id'=>52),
                       array('model_name'=>'ds21','brand_id'=>52),
                       array('model_name'=>'ds23','brand_id'=>52),
                       array('model_name'=>'ds4','brand_id'=>52),
                       array('model_name'=>'ds5','brand_id'=>52),
                       array('model_name'=>'evasion','brand_id'=>52),
                       array('model_name'=>'grand c4 picasso','brand_id'=>52),
                       array('model_name'=>'grand c4 spacetourer','brand_id'=>52),
                       array('model_name'=>'hy  ','brand_id'=>52),
                       array('model_name'=>'jumper','brand_id'=>52),
                       array('model_name'=>'jumpy','brand_id'=>52),
                       array('model_name'=>'mehari','brand_id'=>52),
                       array('model_name'=>'nemo','brand_id'=>52),
                       array('model_name'=>'saxo','brand_id'=>52),
                       array('model_name'=>'sm','brand_id'=>52),
                       array('model_name'=>'spacetourer','brand_id'=>52),
                       array('model_name'=>'visa','brand_id'=>52),
                       array('model_name'=>'xantia','brand_id'=>52),
                       array('model_name'=>'xm','brand_id'=>52),
                       array('model_name'=>'xsara','brand_id'=>52),
                       array('model_name'=>'xsara picasso','brand_id'=>52),
                       array('model_name'=>'zx','brand_id'=>52),



                       array('model_name'=>'1007','brand_id'=>17),
                       array('model_name'=>'104','brand_id'=>17),
                       array('model_name'=>'106','brand_id'=>17),
                       array('model_name'=>'107','brand_id'=>17),
                       array('model_name'=>'108','brand_id'=>17),
                       array('model_name'=>'2008','brand_id'=>17),
                       array('model_name'=>'203','brand_id'=>17),
                       array('model_name'=>'204','brand_id'=>17),
                       array('model_name'=>'205','brand_id'=>17),
                       array('model_name'=>'206','brand_id'=>17),
                       array('model_name'=>'206 cc','brand_id'=>17),
                       array('model_name'=>'206 sw','brand_id'=>17),
                       array('model_name'=>'206+','brand_id'=>17),
                       array('model_name'=>'207','brand_id'=>17),
                       array('model_name'=>'207 cc','brand_id'=>17),
                       array('model_name'=>'207 sw','brand_id'=>17),
                       array('model_name'=>'208','brand_id'=>17),
                       array('model_name'=>'3008','brand_id'=>17),
                       array('model_name'=>'301','brand_id'=>17),
                       array('model_name'=>'304','brand_id'=>17),
                       array('model_name'=>'305','brand_id'=>17),
                       array('model_name'=>'306','brand_id'=>17),
                       array('model_name'=>'307','brand_id'=>17),
                       array('model_name'=>'307 cc','brand_id'=>17),
                       array('model_name'=>'307 sw','brand_id'=>17),
                       array('model_name'=>'308','brand_id'=>17),
                       array('model_name'=>'308 cc','brand_id'=>17),
                       array('model_name'=>'308 sw','brand_id'=>17),
                       array('model_name'=>'309','brand_id'=>17),
                       array('model_name'=>'4007','brand_id'=>17),
                       array('model_name'=>'4008','brand_id'=>17),
                       array('model_name'=>'403','brand_id'=>17),
                       array('model_name'=>'404','brand_id'=>17),
                       array('model_name'=>'405','brand_id'=>17),
                       array('model_name'=>'406','brand_id'=>17),
                       array('model_name'=>'407','brand_id'=>17),
                       array('model_name'=>'407 coupe','brand_id'=>17),
                       array('model_name'=>'407 sw','brand_id'=>17),
                       array('model_name'=>'5008','brand_id'=>17),
                       array('model_name'=>'504','brand_id'=>17),
                       array('model_name'=>'505','brand_id'=>17),
                       array('model_name'=>'508','brand_id'=>17),
                       array('model_name'=>'508 rxh','brand_id'=>17),
                       array('model_name'=>'604','brand_id'=>17),
                       array('model_name'=>'605','brand_id'=>17),
                       array('model_name'=>'607','brand_id'=>17),
                       array('model_name'=>'806','brand_id'=>17),
                       array('model_name'=>'807','brand_id'=>17),
                       array('model_name'=>'bipper','brand_id'=>17),
                       array('model_name'=>'boxer','brand_id'=>17),
                       array('model_name'=>'expert','brand_id'=>17),
                       array('model_name'=>'j5','brand_id'=>17),
                       array('model_name'=>'j9','brand_id'=>17),
                       array('model_name'=>'landtrek','brand_id'=>17),
                       array('model_name'=>'partner','brand_id'=>17),
                       array('model_name'=>'Partner tepee','brand_id'=>17),
                       array('model_name'=>'pick up','brand_id'=>17),
                       array('model_name'=>'rcz','brand_id'=>17),
                       array('model_name'=>'rifter','brand_id'=>17),
                       array('model_name'=>'traveller','brand_id'=>17),

                       array('model_name'=>'12','brand_id'=>19),
                       array('model_name'=>'14','brand_id'=>19),
                       array('model_name'=>'16','brand_id'=>19),
                       array('model_name'=>'30','brand_id'=>19),
                       array('model_name'=>'avantime','brand_id'=>19),
                       array('model_name'=>'b110','brand_id'=>19),
                       array('model_name'=>'b120','brand_id'=>19),
                       array('model_name'=>'b80','brand_id'=>19),
                       array('model_name'=>'captur','brand_id'=>19),
                       array('model_name'=>'clio','brand_id'=>19),
                       array('model_name'=>'espace','brand_id'=>19),
                       array('model_name'=>'estafette','brand_id'=>19),
                       array('model_name'=>'express','brand_id'=>19),
                       array('model_name'=>'express van','brand_id'=>19),
                       array('model_name'=>'fluence','brand_id'=>19),
                       array('model_name'=>'fuego','brand_id'=>19),
                       array('model_name'=>'grand espace','brand_id'=>19),
                       array('model_name'=>'grand modus','brand_id'=>19),
                       array('model_name'=>'grand scenic','brand_id'=>19),
                       array('model_name'=>'kadjar','brand_id'=>19),
                       array('model_name'=>'kangoo','brand_id'=>19),
                       array('model_name'=>'koleos','brand_id'=>19),
                       array('model_name'=>'LAGUNA ','brand_id'=>19),
                       array('model_name'=>'laguna coupe','brand_id'=>19),
                       array('model_name'=>'laguna estate','brand_id'=>19),
                       array('model_name'=>'latitude','brand_id'=>19),
                       array('model_name'=>'mascott','brand_id'=>19),
                       array('model_name'=>'master','brand_id'=>19),
                       array('model_name'=>'megane','brand_id'=>19),
                       array('model_name'=>'megane estate','brand_id'=>19),
                       array('model_name'=>'megane sedan','brand_id'=>19),
                       array('model_name'=>'messenger','brand_id'=>19),
                       array('model_name'=>'microbus','brand_id'=>19),
                       array('model_name'=>'modus','brand_id'=>19),
                       array('model_name'=>'nevada','brand_id'=>19),
                       array('model_name'=>'r11','brand_id'=>19),
                       array('model_name'=>'r18','brand_id'=>19),
                       array('model_name'=>'r19','brand_id'=>19),
                       array('model_name'=>'r20','brand_id'=>19),
                       array('model_name'=>'r21','brand_id'=>19),
                       array('model_name'=>'r25','brand_id'=>19),
                       array('model_name'=>'r4','brand_id'=>19),
                       array('model_name'=>'r5','brand_id'=>19),
                       array('model_name'=>'r8','brand_id'=>19),
                       array('model_name'=>'r9','brand_id'=>19),
                       array('model_name'=>'safrane','brand_id'=>19),
                       array('model_name'=>'samsung sm3','brand_id'=>19),
                       array('model_name'=>'scenic','brand_id'=>19),
                       array('model_name'=>'spider','brand_id'=>19),
                       array('model_name'=>'super 5','brand_id'=>19),
                       array('model_name'=>'symbol','brand_id'=>19),
                       array('model_name'=>'talisman','brand_id'=>19),
                       array('model_name'=>'trafic','brand_id'=>19),
                       array('model_name'=>'twingo','brand_id'=>19),
                       array('model_name'=>'twizy','brand_id'=>19),
                       array('model_name'=>'vel satis','brand_id'=>19),
                       array('model_name'=>'zoe','brand_id'=>19),

                       array('model_name'=>'adam','brand_id'=>101),
                       array('model_name'=>'agila','brand_id'=>101),
                       array('model_name'=>'antara','brand_id'=>101),
                       array('model_name'=>'ascona','brand_id'=>101),
                       array('model_name'=>'astra','brand_id'=>101),
                       array('model_name'=>'calibra','brand_id'=>101),
                       array('model_name'=>'campo','brand_id'=>101),
                       array('model_name'=>'combo','brand_id'=>101),
                       array('model_name'=>'combo cargo','brand_id'=>101),
                       array('model_name'=>'combo life','brand_id'=>101),
                       array('model_name'=>'corsa','brand_id'=>101),
                       array('model_name'=>'crossland ','brand_id'=>101),
                       array('model_name'=>'frontera','brand_id'=>101),
                       array('model_name'=>'grandland x','brand_id'=>101),
                       array('model_name'=>'gt','brand_id'=>101),
                       array('model_name'=>'insignia','brand_id'=>101),
                       array('model_name'=>'kadett','brand_id'=>101),
                       array('model_name'=>'meriva','brand_id'=>101),
                       array('model_name'=>'mokka','brand_id'=>101),
                       array('model_name'=>'mokka x ','brand_id'=>101),
                       array('model_name'=>'monterey','brand_id'=>101),
                       array('model_name'=>'movano','brand_id'=>101),
                       array('model_name'=>'omega','brand_id'=>101),
                       array('model_name'=>'opc','brand_id'=>101),
                       array('model_name'=>'rekord','brand_id'=>101),
                       array('model_name'=>'signum','brand_id'=>101),
                       array('model_name'=>'sintra','brand_id'=>101),
                       array('model_name'=>'speedster','brand_id'=>101),
                       array('model_name'=>'tigra','brand_id'=>101),
                       array('model_name'=>'vectra','brand_id'=>101),
                       array('model_name'=>'vivaro','brand_id'=>101),
                       array('model_name'=>'zafira','brand_id'=>101),

                       array('model_name'=>'b max','brand_id'=>6),
                       array('model_name'=>'bedford','brand_id'=>6),
                       array('model_name'=>'c max','brand_id'=>6),
                       array('model_name'=>'capri','brand_id'=>6),
                       array('model_name'=>'connect','brand_id'=>6),
                       array('model_name'=>'cougar','brand_id'=>6),
                       array('model_name'=>'courrier','brand_id'=>6),
                       array('model_name'=>'crown victoria','brand_id'=>6),
                       array('model_name'=>'e350','brand_id'=>6),
                       array('model_name'=>'ecosport','brand_id'=>6),
                       array('model_name'=>'edge','brand_id'=>6),
                       array('model_name'=>'escape','brand_id'=>6),
                       array('model_name'=>'escort','brand_id'=>6),
                       array('model_name'=>'everest','brand_id'=>6),
                       array('model_name'=>'excursion','brand_id'=>6),
                       array('model_name'=>'expedition','brand_id'=>6),
                       array('model_name'=>'explorer','brand_id'=>6),
                       array('model_name'=>'f-150','brand_id'=>6),
                       array('model_name'=>'f-250','brand_id'=>6),
                       array('model_name'=>'f-350','brand_id'=>6),
                       array('model_name'=>'fiesta','brand_id'=>6),
                       array('model_name'=>'flex','brand_id'=>6),
                       array('model_name'=>'focus','brand_id'=>6),
                       array('model_name'=>'focus 4P','brand_id'=>6),
                       array('model_name'=>'focus c-max','brand_id'=>6),
                       array('model_name'=>'fusion','brand_id'=>6),
                       array('model_name'=>'galaxy','brand_id'=>6),
                       array('model_name'=>'gt','brand_id'=>6),
                       array('model_name'=>'ka','brand_id'=>6),
                       array('model_name'=>'kuga','brand_id'=>6),
                       array('model_name'=>'maverick','brand_id'=>6),
                       array('model_name'=>'minibus','brand_id'=>6),
                       array('model_name'=>'mondeo','brand_id'=>6),
                       array('model_name'=>'mustang','brand_id'=>6),
                       array('model_name'=>'orion','brand_id'=>6),
                       array('model_name'=>'pick-up','brand_id'=>6),
                       array('model_name'=>'probe','brand_id'=>6),
                       array('model_name'=>'puma','brand_id'=>6),
                       array('model_name'=>'ranger','brand_id'=>6),
                       array('model_name'=>'s-max','brand_id'=>6),
                       array('model_name'=>'scorpio','brand_id'=>6),
                       array('model_name'=>'sierra','brand_id'=>6),
                       array('model_name'=>'street ka','brand_id'=>6),
                       array('model_name'=>'super duty','brand_id'=>6),
                       array('model_name'=>'taunus','brand_id'=>6),
                       array('model_name'=>'thunderbird','brand_id'=>6),
                       array('model_name'=>'tourneo connect','brand_id'=>6),
                       array('model_name'=>'tourneo custom','brand_id'=>6),
                       array('model_name'=>'transit','brand_id'=>6),
                       array('model_name'=>'victoria','brand_id'=>6),


                       array('model_name'=>'accent','brand_id'=>8),
                       array('model_name'=>'atos','brand_id'=>8),
                       array('model_name'=>'azera','brand_id'=>8),
                       array('model_name'=>'centennial','brand_id'=>8),
                       array('model_name'=>'county','brand_id'=>8),
                       array('model_name'=>'coupe','brand_id'=>8),
                       array('model_name'=>'creta','brand_id'=>8),
                       array('model_name'=>'elantra','brand_id'=>8),
                       array('model_name'=>'equus','brand_id'=>8),
                       array('model_name'=>'excel','brand_id'=>8),
                       array('model_name'=>'galloper','brand_id'=>8),
                       array('model_name'=>'genesis','brand_id'=>8),
                       array('model_name'=>'getz','brand_id'=>8),
                       array('model_name'=>'grand i10','brand_id'=>8),
                       array('model_name'=>'grand santa fe ','brand_id'=>8),
                       array('model_name'=>'grandeur','brand_id'=>8),
                       array('model_name'=>'h','brand_id'=>8),
                       array('model_name'=>'h1','brand_id'=>8),
                       array('model_name'=>'h100','brand_id'=>8),
                       array('model_name'=>'h200','brand_id'=>8),
                       array('model_name'=>'h350','brand_id'=>8),
                       array('model_name'=>'i10','brand_id'=>8),
                       array('model_name'=>'i20','brand_id'=>8),
                       array('model_name'=>'i30','brand_id'=>8),
                       array('model_name'=>'i40','brand_id'=>8),
                       array('model_name'=>'ioniq','brand_id'=>8),
                       array('model_name'=>'ix35','brand_id'=>8),
                       array('model_name'=>'ix55','brand_id'=>8),
                       array('model_name'=>'kona','brand_id'=>8),
                       array('model_name'=>'lantra','brand_id'=>8),
                       array('model_name'=>'matrix','brand_id'=>8),
                       array('model_name'=>'pony','brand_id'=>8),
                       array('model_name'=>'santa fe','brand_id'=>8),
                       array('model_name'=>'santamo','brand_id'=>8),
                       array('model_name'=>'satellite','brand_id'=>8),
                       array('model_name'=>'sonata','brand_id'=>8),
                       array('model_name'=>'sonica','brand_id'=>8),
                       array('model_name'=>'terracan','brand_id'=>8),
                       array('model_name'=>'trajet','brand_id'=>8),
                       array('model_name'=>'tucson','brand_id'=>8),
                       array('model_name'=>'veloster','brand_id'=>8),
                       array('model_name'=>'veracruz','brand_id'=>8),
                       array('model_name'=>'xg','brand_id'=>8),

                       array('model_name'=>'126','brand_id'=>5),
                       array('model_name'=>'127','brand_id'=>5),
                       array('model_name'=>'131','brand_id'=>5),
                       array('model_name'=>'500','brand_id'=>5),
                       array('model_name'=>'500c','brand_id'=>5),
                       array('model_name'=>'500l','brand_id'=>5),
                       array('model_name'=>'500x','brand_id'=>5),
                       array('model_name'=>'850 coupe','brand_id'=>5),
                       array('model_name'=>'albea','brand_id'=>5),
                       array('model_name'=>'barchetta','brand_id'=>5),
                       array('model_name'=>'bertone','brand_id'=>5),
                       array('model_name'=>'brava','brand_id'=>5),
                       array('model_name'=>'bravo','brand_id'=>5),
                       array('model_name'=>'burstner','brand_id'=>5),
                       array('model_name'=>'cinquecento','brand_id'=>5),
                       array('model_name'=>'coupe','brand_id'=>5),
                       array('model_name'=>'croma','brand_id'=>5),
                       array('model_name'=>'doblo','brand_id'=>5),
                       array('model_name'=>'ducato','brand_id'=>5),
                       array('model_name'=>'fiorino','brand_id'=>5),
                       array('model_name'=>'freemont','brand_id'=>5),
                       array('model_name'=>'fullback','brand_id'=>5),
                       array('model_name'=>'grande punto','brand_id'=>5),
                       array('model_name'=>'idea','brand_id'=>5),
                       array('model_name'=>'linea','brand_id'=>5),
                       array('model_name'=>'marea','brand_id'=>5),
                       array('model_name'=>'multipla','brand_id'=>5),
                       array('model_name'=>'palio','brand_id'=>5),
                       array('model_name'=>'panda','brand_id'=>5),
                       array('model_name'=>'punto','brand_id'=>5),
                       array('model_name'=>'regata','brand_id'=>5),
                       array('model_name'=>'ritmo','brand_id'=>5),
                       array('model_name'=>'scudo','brand_id'=>5),
                       array('model_name'=>'sedici','brand_id'=>5),
                       array('model_name'=>'seicento','brand_id'=>5),
                       array('model_name'=>'siena','brand_id'=>5),
                       array('model_name'=>'stilo','brand_id'=>5),
                       array('model_name'=>'talento','brand_id'=>5),
                       array('model_name'=>'tempra','brand_id'=>5),
                       array('model_name'=>'tipo','brand_id'=>5),
                       array('model_name'=>'tipo hatchback','brand_id'=>5),
                       array('model_name'=>'toledo','brand_id'=>5),
                       array('model_name'=>'ulysse','brand_id'=>5),
                       array('model_name'=>'uno','brand_id'=>5),

                    );
                       DB::table('car_models')->insert($renault);
}
}
